Repository TeamWazard/wazard-front, pull requests merged in 2023-06, with the labels that each got.

#78 [Feat/#77] 알바생 화면 - 대타기록 페이지 및 폼 제작
  src/App.js
  src/components/LeftMenuAlba.js
  src/pages/alba/inAlba/AlbaContract.js
  src/pages/alba/inAlba/AlbaReplace.js
  src/pages/alba/inAlba/AlbaReplaceForm.js
  src/redux-toolkit/albaModule/AlbaReplaceSlice.js
  src/redux-toolkit/store.js
  src/style/alba/albaReplace.scss
Labels: feature, 김정환, size/XL

#79 [Feat/#75] 고용주화면 - 초대 대기 목록 조회
  src/pages/company/inCompany/CompanyInvite.js
  src/pages/main/ButtonChoose.js
  src/pages/main/SignUpChoose.js
  src/pages/main/SignUpChoose.scss
  src/redux-toolkit/albaModule/AlbaWaitListSlice.js
  src/redux-toolkit/store.js
  src/style/company/company.scss
Labels: feature, 윤서영, size/L

#82 [Feat]로그인 api 적용 및 수정
  src/components/Header.js
  src/components/HeaderAlba.js
  src/pages/company/CompanyList.js
  src/pages/main/Login.js
  src/redux-toolkit/store.js
  src/redux-toolkit/userSlice.js
Labels: feature, 김정환, size/L

#85 [Fix/#83]폰트 변경 및 로그아웃, 로컬스토리지 설정
  public/index.html
  src/components/Header.js
  src/components/HeaderAlba.js
  src/components/LeftMenuAlba.js
  src/components/LeftMenuMyPage.js
  src/pages/alba/MyPageAlbaRecord.js
  src/pages/alba/inAlba/AlbaReplace.js
  src/pages/alba/inAlba/AlbaReplaceForm.js
  src/pages/company/inCompany/CompanyMain.scss
  src/pages/main/Login.js
  src/style/alba/albaRecord.scss
  src/style/alba/albaReplace.scss
  src/style/alba/albaStyle.scss
  src/style/calendar/Calendar.scss
  src/style/company/company.scss
  src/style/company/companyAlba.scss
  src/style/mypage/mypage.scss
Labels: fix, 김정환, size/L

#90 [Feat/#88] 알바생화면 - 초대 동의 화면
  src/App.js
  src/components/company/CompanyListView.js
  src/pages/alba/AlbaInvitedContract.js
  src/pages/alba/AlbaInvitedPage.js
  src/pages/company/CompanyList.js
  src/pages/company/inCompany/CompanyAlba.js
  src/pages/company/inCompany/CompanyInvite.js
  src/pages/company/inCompany/CompanyInviteContract.js
  src/pages/company/inCompany/CompanyMain.js
  src/pages/company/inCompany/CompanyMain.scss
  src/pages/main/Login.js
  src/pages/main/SignUpChoose.js
  src/pages/main/SignUpChoose.scss
  src/redux-toolkit/albaModule/AlbaCompanyListReducer.js
  src/redux-toolkit/store.js
  src/redux-toolkit/userSlice.js
  src/style/alba/albaStyle.scss
  src/style/company/companyAlba.scss
  src/style/components/Contract.scss
  src/utils/apis/authAPI.js
  src/utils/apis/axios.js
  src/utils/apis/companyAPI.js
Labels: feature, 윤서영, size/XXL
