Repository TeamWazard/wazard-front, pull requests merged in 2023-04, with the labels that each got.

#9 [Feat/#6] 고용주, 알바생 선택 화면 구현 및 화면 연결
  src/App.js
  src/imgs/ceoIcon.svg
  src/imgs/pjIcon.svg
  src/index.scss
  src/pages/main/ButtonChoose.js
  src/pages/main/ButtonChoose.scss
  src/pages/main/Login.js
  src/pages/main/Login.scss
  src/pages/main/SignUpChoose.js
Labels: feature, 김정환, size/L

#13 Create README.md
  README.md
Labels: size/S

#14 [Feat/#12] 고용주 화면 - 운영중인 업장 목록 조회화면
  package-lock.json
  package.json
  src/App.js
  src/hooks/UseImgSave.js
  src/hooks/useInputNum.js
  src/pages/company/CompanyEditor.js
  src/pages/company/companyList.js
  src/pages/main/SignUpChoose.js
  src/redux-toolkit/createSlice.js
  src/redux-toolkit/messageSlice.js
  src/redux-toolkit/store.js
  src/style/company/company.scss
Labels: size/XL

#17 [Feat/#11] 메인 페이지 TopBar, 좌측 메뉴 컴포넌트 구현 및 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/DOCS_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/FIX_REQUEST.md
  .github/ISSUE_TEMPLATE/HOTFIX_REQUEST.md
  .github/ISSUE_TEMPLATE/REFACTOR_REQUEST.md
  .github/ISSUE_TEMPLATE/TEST_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/App.js
  src/App.scss
  src/components/Header.js
  src/components/LeftMenuCeo.js
  src/imgs/topbar.svg
  src/pages/main/CeoMain.js
  src/pages/main/CeoMain2.js
  src/pages/main/CeoMain3.js
  src/pages/main/CeoMain4.js
Labels: feature, 김정환, size/L

#19 [Feat/#16] 고용주화면 - 캘린더 메인 화면
  jsconfig.json
  package-lock.json
  package.json
  src/App.js
  src/components/company/CompanySave.js
  src/pages/company/CompanyAdd.js
  src/pages/company/CompanyEdit.js
  src/pages/company/CompanyEditor.js
  src/pages/company/companyList.js
  src/pages/company/inCompany/CompanyMain.js
  src/pages/main/SignUpChoose.js
  src/redux-toolkit/createSlice.js
  src/style/calendar/Calendar.scss
  src/style/company/company.scss
  src/style/company/company_main_calender.scss
Labels: feature, 윤서영, size/XL

#20 [Feat/#16] 고용주화면 - 캘린더 메인 화면 2 - 알바생 목록 조회
  jsconfig.json
  src/pages/company/inCompany/CompanyMain.js
  src/pages/company/inCompany/CompanyMain.scss
  src/style/calendar/Calendar.scss
  src/style/company/company_main_calender.scss
Labels: feature, 윤서영, size/L

#25 [Fix/#21] 회원가입 페이지 디자인 & 기능 수정, 코드 정리
  src/components/Button_test.js
  src/components/Input.js
  src/components/LeftMenuCeo.js
  src/components/company/CompanySave.js
  src/hooks/useInputNum.js
  src/pages/company/companyList.js
  src/pages/company/inCompany/CompanyMain.js
  src/pages/company/inCompany/CompanyMain.scss
  src/pages/main/SignUpChoose.js
  src/pages/main/SignUpChoose.scss
  src/style/company/company.scss
Labels: fix, 윤서영, size/L
