Repository TeamWazard/wazard-front, pull requests merged in 2023-05, with the labels that each got.

#28 [Fix/#27] wazard 로고 클릭시 페이지 이동, 관리자 페이지 클릭시 페이지 이동 수정
  src/components/Header.js
  src/components/LeftMenuCeo.js
  src/pages/company/CompanyList.js
  src/pages/company/inCompany/CompanyAlbaList.js
  src/pages/company/inCompany/CompanyAlbaSalary.js
  src/pages/company/inCompany/CompanyMain.js
Labels: fix, 김정환, size/S

#30 [Fix/#29] 좌측 메뉴 페이지 이동 구현된 페이지에 연결
  src/App.js
  src/components/LeftMenuCeo.js
  src/pages/company/inCompany/CompanyAlbaList.js
  src/pages/main/CeoMain3.js
  src/pages/main/CeoMain4.js
Labels: fix, 김정환, size/L

#32 [Feat/#23] 고용주화면 - 알바생관리 (특정 알바생 근무조회 화면)
  package-lock.json
  package.json
  src/App.js
  src/pages/company/inCompany/CompanyAlba.js
  src/pages/company/inCompany/CompanyAlba.scss
  src/pages/company/inCompany/CompanyAlbaList.js
  src/pages/company/inCompany/CompanyMain.js
  src/pages/main/SignUpChoose.scss
  src/redux-toolkit/albaListSlice.js
  src/redux-toolkit/createSlice.js
  src/style/calendar/Calendar.scss
  src/style/company/companyAlba.scss
Labels: feature, size/L

#34 [Feat/#33]: 고용주화면 - 알바생 email 초대 페이지
  src/App.js
  src/components/LeftMenuCeo.js
  src/pages/company/inCompany/CompanyAlba.js
  src/pages/company/inCompany/CompanyAlba.scss
  src/pages/company/inCompany/CompanyInvite.js
  src/style/company/company.scss
Labels: feature, 윤서영, size/L

#36 [Feat/#31]: 고용주화면 - 특정 알바생 계약정보 조회 화면 구현(2-1b)
  package-lock.json
  src/App.js
  src/pages/company/inCompany/CompanyAlbaList.js
  src/pages/company/inCompany/CompanyContractEdit.js
  src/pages/company/inCompany/CompanyContractEditCheck.js
  src/redux-toolkit/albaListSlice.js
  src/redux-toolkit/albaSalarySlice.js
  src/style/company/companyAlba.scss
Labels: feature, 김정환, size/L

#38 [Feat/#35] 고용주화면 - QR코드 조회
  package-lock.json
  package.json
  src/App.js
  src/components/LeftMenuCeo.js
  src/pages/company/inCompany/CompanyQR.js
  src/style/company/company.scss
Labels: feature, 윤서영, size/L

#41 [Feat/#40]: 고용주- 좌측 메뉴 컴포넌트 알바생 초대, qr코드 조회 페이지 id값 수정
  src/pages/company/inCompany/CompanyInvite.js
  src/pages/company/inCompany/CompanyQR.js
Labels: fix, 김정환, size/XS

#42 [Feat/#37]: 알바생-좌측 메뉴 컴포넌트 제작 및 알바생 페이지 상단바 제작
  src/App.js
  src/components/HeaderAlba.js
  src/components/LeftMenuAlba.js
  src/pages/main/AlbaMainTest.js
  src/pages/main/AlbaTest1.js
  src/pages/main/AlbaTest2.js
  src/pages/main/AlbaTest3.js
Labels: feature, 김정환, size/L

#45 [Fix/#43] 고용주화면 - 업장 등록화면(카카오 도로명주소, 업종 추가)
  package-lock.json
  src/App.js
  src/components/AddressPost.js
  src/components/company/CompanyListView.js
  src/components/company/CompanySave.js
  src/index.js
  src/pages/alba/AlbaListPage.js
  src/pages/company/CompanyList.js
  src/redux-toolkit/albaModule/AlbaCompanyListReducer.js
  src/redux-toolkit/createSlice.js
  src/redux-toolkit/messageSlice.js
  src/redux-toolkit/store.js
  src/style/alba/albaCompanyList.scss
  src/style/company/company.scss
  src/style/components/AddressPost.scss
Labels: fix, 윤서영, size/XL

#46 [Fix/#44] 고용주화면 - 알바생 리스트 화면 정보 수정
  package.json
  src/pages/company/inCompany/CompanyAlbaList.js
  src/redux-toolkit/albaListSlice.js
  src/style/company/companyAlba.scss
Labels: fix, 김정환, size/L

#47 [Feat/#39] 알바생화면 - 알바중인 업장 목록페이지
  src/App.js
  src/pages/alba/AlbaInvitedPage.js
  src/pages/alba/AlbaListPage.js
  src/style/alba/albaCompanyList.scss
  src/style/alba/albaStyle.scss
  src/style/company/company.scss
Labels: feature, 윤서영, size/L

#50 [Feat/#49] 알바생화면 - 알바생 계약정보페이지 구현
  src/App.js
  src/pages/alba/AlbaContract.js
  src/redux-toolkit/albaModule/AlbaContractSlice.js
  src/redux-toolkit/store.js
Labels: feature, 김정환, size/L

#51 [Feat/#48] Footer 하단바 디자인
  src/App.js
  src/components/Footer.js
  src/components/Footer_2.js
  src/components/ScrollToTop.js
  src/pages/alba/AlbaInvitedPage.js
  src/pages/alba/AlbaListPage.js
  src/style/alba/albaCompanyList.scss
  src/style/alba/albaStyle.scss
  src/style/company/company.scss
Labels: feature, 윤서영, size/L

#55 [Feat/#48] 상단바(Header) 우측 드롭다운 구현
  src/components/Header.js
  src/components/HeaderAlba.js
  src/style/components/Header.scss
Labels: feature, 김정환, size/M

#58 [Feat/#53] 알바생화면 - 업장 클릭시 화면
  package-lock.json
  package.json
  src/App.js
  src/components/Footer.js
  src/components/Footer_2.js
  src/components/Header.js
  src/components/LeftMenuCeo.js
  src/components/company/CompanyListView.js
  src/pages/alba/AlbaInvitedPage.js
  src/pages/alba/inAlba/AlbaMainPage.js
  src/style/alba/albaStyle.scss
Labels: feature, 윤서영, size/L

#61 [Feat/#54] 알바생화면 - 알바생 본인의 출퇴근 조회 구현
  public/index.html
  src/App.js
  src/pages/alba/inAlba/AlbaAttendance.js
  src/style/alba/albaStyle.scss
  src/style/company/companyAlba.scss
Labels: feature, 윤서영, size/L

#66 [Feat/#57] 마이페이지(알바) - 과거 알바기록 조회 페이지 구현
  src/App.js
  src/components/LeftMenuAlba.js
  src/components/LeftMenuMyPage.js
  src/pages/alba/MyPageAlbaRecord.js
  src/pages/alba/MyPageAlbaRecordCheck.js
  src/pages/alba/inAlba/AlbaMainPage.js
  src/pages/company/inCompany/CompanyAlbaList.js
  src/redux-toolkit/albaModule/AlbaRecordListSlice.js
  src/redux-toolkit/store.js
  src/style/alba/albaRecord.scss
Labels: feature, 김정환, size/L

#67 [Feat/#65] 고용주화면 - 알바생 출퇴근 기록 (QR->고용주화면에서 기록)
  package-lock.json
  package.json
  src/components/LeftMenuCeo.js
  src/components/Modal.js
  src/pages/company/CompanyList.js
  src/pages/company/inCompany/CompanyQR.js
  src/pages/main/ButtonChoose.scss
  src/style/company/company.scss
Labels: feature, 윤서영, size/L

#73 [Feat/#71] 마이페이지 - 본인인증 후 회원정보 수정
  src/App.js
  src/components/Radio.js
  src/components/Radio.scss
  src/components/certification/Password.js
  src/pages/main/MyPageCertification.js
  src/pages/main/MyPageEdit.js
  src/style/mypage/mypage.scss
Labels: feature, 윤서영, size/XL

#76 [Feat/#70] 고용주 화면 - 알바생 계약정보 등록 및 초대메일 전송 페이지 구현
  src/App.js
  src/components/LeftMenuCeo.js
  src/pages/company/inCompany/CompanyInviteContract.js
  src/style/company/companyAlba.scss
Labels: feature, 김정환, size/L
